public fun foo() {
    let x = 1
    // TODO: why does this produce duplicate errors?
    x + 1 = 2
}

// args: check
// expected exit status: 1
// expected stdout:
// Error: Expected a symbol after this.
// ---| src/test_files/check/assign_not_lvalue.gdn:4:7
//   2|     let x = 1
//   3|     // TODO: why does this produce duplicate errors?
//   4|     x + 1 = 2
//   5| }     ^
// 
// Error: Expected a symbol after this.
// ---| src/test_files/check/assign_not_lvalue.gdn:4:7
//   2|     let x = 1
//   3|     // TODO: why does this produce duplicate errors?
//   4|     x + 1 = 2
//   5| }     ^
// 
// Error: Expected `}` after this.
// ---| src/test_files/check/assign_not_lvalue.gdn:4:7
//   2|     let x = 1
//   3|     // TODO: why does this produce duplicate errors?
//   4|     x + 1 = 2
//   5| }     ^
// 
// Error: Expected a symbol after this.
// ---| src/test_files/check/assign_not_lvalue.gdn:4:7
//   2|     let x = 1
//   3|     // TODO: why does this produce duplicate errors?
//   4|     x + 1 = 2
//   5| }     ^

