external fun foo() {
    let x = 1
    // TODO: why does this produce duplicate errors?
    x + 1 = 2
}

// args: check
// expected exit status: 1
// expected stdout:
// Error: Expected an expression, but got `=`.
// ---| src/test_files/check/assign_not_lvalue.gdn:4:11
// 2  |     let x = 1
// 3  |     // TODO: why does this produce duplicate errors?
// 4  |     x + 1 = 2
// 5  | }         ^
// 
// Error: Expected `}`, but got `=`.
// ---| src/test_files/check/assign_not_lvalue.gdn:4:11
// 2  |     let x = 1
// 3  |     // TODO: why does this produce duplicate errors?
// 4  |     x + 1 = 2
// 5  | }         ^
// 
// Error: Expected an expression, but got `=`.
// ---| src/test_files/check/assign_not_lvalue.gdn:4:11
// 2  |     let x = 1
// 3  |     // TODO: why does this produce duplicate errors?
// 4  |     x + 1 = 2
// 5  | }         ^

