external fun foo(_f: Fun<(Int, Int)>) {}

// args: check
// expected exit status: 1
// expected stdout:
// Error: Fun takes 2 type arguments, but got 1 argument.
// ---| src/test_files/check/bad_fun_arity.gdn:1:26
//   1| external fun foo(_f: Fun<(Int, Int)>) {}
//   2|                          ^^^^^^^^^^
//   3| // args: check

